model:
    arch: segnet
data:
    dataset: cityscapes
    train_split: train
    val_split: val
    img_rows: 380
    img_cols: 500
    path: /media/manuel/OS/Datasets/Cityscapes
training:
    n_workers: 7
    train_iters: 148001
    batch_size: 2
    val_interval: 500
    print_interval: 25
    loss:
        name: 'cross_entropy'
    optimizer:
        name: 'sgd'
        lr: 1.0e-4
    l_rate: 1.0e-4
    lr_schedule:
        name: 'constant_lr'
    momentum: 0.99
    weight_decay: 0.0005
    resume: segnet_cityscapes_best_model.pkl
    visdom: False
